# action.yml
name: 'PAT'
description: 'Various Guestlogix Pipeline Automations'
inputs:
  pipeline-command:  # id of input
    description: 'The desired script to run in the action'
    required: true
    default: 'pat --help'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # entrypoint: 'ENTRYPOINT ["/tmp/entry.sh"]' # idk why this doesn't work, would be nice to exclude entry from image so it can be used as a build step.
  args:
    - ${{ inputs.pipeline-command }}
branding:
  icon: 'flag'  
  color: 'green'