# action.yml
name: 'PAT'
description: 'Various Guestlogix Pipeline Automations'
inputs:
  pipeline-command:  # id of input
    description: 'The cli commands to run'
    required: false
    default: 'pat --help'
runs:
  using: 'docker'
  image: './actions/Dockerfile'
  args:
    - ${{ inputs.arguments }}