endpoint: https://guestlogix.atlassian.net
user: hgoddard@guestlogix.com
custom-commands:
- name: ctask
  help: creates a task in the given project
  options:
    - name: project
      short: p
      default: $JIRA_PROJECT
    - name: description
      short: d
      default: ""
  args:
    - name: summary
      required: true
  script: |-
    {{jira}} create --issuetype=Task -o summary="{{args.summary}}" -o description="{{options.description}}" -p {{options.project}} --noedit